### PR TITLE
add implementations of hal::blocking::delay traits

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5277ed9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5277ed935744602dd0ffd4d027b9890eb7dff66e with merge 466dd82fc2282e591b30af6295291e4d8cb4cf77...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 850d88f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 850d88f046a4251301911a73a1ab1f09fd0088c3 with merge 0dc881bdc2fa68a6195a8ea60e5e1021f06f0908...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/linux-embedded-hal/builds/332475937?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0dc881bdc2fa68a6195a8ea60e5e1021f06f0908 to master...

**Pull request merged**
