### PR TITLE
disable the default features of the cast dependency

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d1e350 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d1e3502011ee682ee5a77ed558990b739294d7c with merge 17ec9f5f69b9015550270a17cd09a995ec4865ca...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/linux-embedded-hal/builds/332513885?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 17ec9f5f69b9015550270a17cd09a995ec4865ca to master...

**Pull request merged**
